service: serverless-webcron

provider:
  name: aws
  runtime: nodejs6.10
  stage: production
  region: ap-northeast-1
  timeout: 30
  environment:
    DYNAMODB_TABLE_NAME: ${file(./secrets.yml):dynamodb_table_name}
    SLACK_WEBHOOK_URL: ${file(./secrets.yml):slack_webhook_url}

functions:
  ping: {handler: handler.ping}
  site: {handler: handler.site}
  sites: {handler: handler.sites}
  execute:
    handler: handler.execute
    events:
      - schedule: cron(0 19 * * ? *)
  
resources:
  Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${file(./secrets.yml):dynamodb_table_name}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    DynamoDBIamPolicy:
      Type: AWS::IAM::Policy
      DependsOn: DynamoDbTable
      Properties:
        PolicyName: serverless-webcron-dynamodb
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DescribeTable
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:Scan
              Resource: arn:aws:dynamodb:*:*:table/${file(./secrets.yml):dynamodb_table_name}
        Roles:
          - Ref: IamRoleLambdaExecution
