service: lambda-webcron

provider:
  name: aws
  runtime: nodejs6.10
  stage: production
  region: ap-northeast-1
  timeout: 30

functions:
  execute: {handler: handler.execute}
  ping: {handler: handler.ping}
  site: {handler: handler.site}
  sites: {handler: handler.sites}

resources:
  Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: sites
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    DynamoDBIamPolicy:
      Type: AWS::IAM::Policy
      DependsOn: DynamoDbTable
      Properties:
        PolicyName: lambda-dynamodb
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DescribeTable
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:Scan
              Resource: arn:aws:dynamodb:*:*:table/sites
        Roles:
          - Ref: IamRoleLambdaExecution
