version: 2

jobs:
  build:
    docker:
      - image: circleci/node:6.10.3
      - image: quay.io/henry40408/dynamodb:v1.0.1
    working_directory: ~/serverless-webcron
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths: [node_modules]
      - run: yarn ci
